apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: "StrongP@ssw0rd!"
  mysql-replication-password: "ReplP@ssw0rd!"
  mysql-app-password: "AppP@ssw0rd!"
