apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod

spec:
  containers:
    - name: mysql-container
      image: mysql:8.0
      # $ docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -d mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306